#!/bin/bash -e

ME=$(basename $0)
DIR=$(dirname $0)
PROGRAM=frontend.py
CONFIG=$DIR/config.ini

flush_stdin() {
  while read -t 1 -n 10000 _; do :; done
}

read_config() {
  DISK=$(awk -F "=" '/disk/ {print $2}' $CONFIG | sed 's/\r$//')
  MOUNTPOINT=$(awk -F "=" '/mountpoint/ {print $2}' $CONFIG | sed 's/\r$//')

  [ -n "$DISK" -a -n "$MOUNTPOINT" ] || return 1
  return 0
}

run_program() {
  python $DIR/$PROGRAM
}

read_config

echo "$ME starting..."

while true; do
  sleep 3

  flush_stdin
  clear

  if ! run_program; then
    echo "Error: abrupt program exit"
    sleep 5
    sudo remount_usb_drive $DISK $MOUNTPOINT
    echo -n "$ME restarting..."
  fi
done
